galaxy_info:
  author: Ramon Bastidas
  description: Installs Kubernetes Cluster
  company: Red Hat

  license: Apache-2.0

  min_ansible_version: 1.2

  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags: [
    cncf
    cni
    kubeadm
    kubelet
    kubernetes
  ]

dependencies: []
