- name: sysctl-system
  command: sysctl --system

- name: restart kubelet
  service:
    name: kubelet
    state: restarted

- name: kill kubeapi
  command: pkill kube-apiserver
  ignore_errors: yes
  listen: "restart kubeapi"

- name: restart kubelet to restart kubeapi
  service:
    name: kubelet
    state: restarted
  listen: "restart kubeapi"
